experiment(ark-zkey): Use rkyv for faster loading
Doesn't currently work due to:

error[E0277]: the trait bound `ProvingKey<ark_ec::models::bn::Bn<ark_bn254::Config>>: Archive` is not satisfied
  --> ark-zkey/src/lib.rs:22:30
   |
22 | #[derive(Archive, Serialize, Deserialize, Clone, Debug, PartialEq)]
   |                              ^^^^^^^^^^^ the trait `Archive` is not implemented for `ProvingKey<ark_ec::models::bn::Bn<ark_bn254::Config>>`
   |
   = help: the following other types implement trait `Archive`:
             bool
             char
             isize
             i8
             i16
             i32
             i64
             i128
           and 139 others
   = help: see issue #48214
   = note: this error originates in the derive macro `Deserialize` (in Nightly builds, run with -Z macro-backtrace for more info)

Unclear how complex it is to fix, need to either:
- Implement Archive manually for `ProvingKey<ark_ec::models::bn::Bn<ark_bn254::Config>>`
- Use a wrapper type